
export const PRODUCTS_REQUEST_SUCCESS = "PRODUCTS_REQUEST_SUCCESS" 
export const PRODUCTS_REQUEST_FAIL = "PRODUCTS_REQUEST_FAIL"


export const ADD_TO_CART = "ADD_TO_CART"
export const REQUEST_FAIL ="REQUEST_FAIL"

export const REMOVE_FROM_CART = "REMOVE_FROM_CART"

export const QUANTITY_INC = "QUANTITY_INC"
export const QUANTITY_DEC = "QUANTITY_DEC"

